apiVersion: v1
kind: ConfigMap
metadata:
  name: study-member-configmap
data:
  application-dev.yml: |
    server:
      port: 8080
    spring:
      datasource:
        url: jdbc:mysql://mysql-jdbc-external-service/study-member?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          connection-test-query: SELECT 1
          validation-timeout: 5000
      jpa:
        hibernate:
          ddl-auto: update
        generate-ddl: true
        show-sql: true
        open-in-view: false